"""
This module provides configuration options and fixtures for pytest.

"""
import pytest
from src_py._helpers import data


def pytest_html_report_title(report):
    """
    Set the title of the HTML report generated by pytest.

    :param report: The report object representing the generated HTML report.
    :type report: pytest_html.plugin.HookReport

    """
    report.title = "PyTest Report"


@pytest.fixture
def stock_prices_fixture():
    """
    Fixture for providing sample stock prices data for testing.

    This fixture loads a sample CSV file containing stock prices data for testing purposes.

    Returns:
    pandas.DataFrame: DataFrame containing the sample stock prices data.

    Example:
    >>> stock_prices_fixture()
             date    ABC     EFG    XYZ
    0  2017-09-05  162.63  154.52  63.95
    1  2017-09-06  161.13  154.45  62.23
    2  2017-09-07  161.26  155.68  60.46
    3  2017-09-08  158.05  155.86  59.35
    4  2017-09-11  161.29  157.17  58.24
    5  2017-09-12  161.09  156.71  58.71
    6  2017-09-13  159.29  155.54  60.33
    """

    return data.load_stock_prices(csv_path='data/stock_prices.csv')
